const BOTS=[{id:"floor",name:"FLOOR",task:"Floor deltas and listing dumps.",last:"scan 4s"},{id:"tape",name:"TAPE",task:"Sales velocity vs baseline.",last:"scan 6s"},{id:"book",name:"BOOK",task:"Bid vs floor, listed %.",last:"scan 9s"},{id:"hold",name:"HOLD",task:"Holders and concentration.",last:"scan 18s"},{id:"wash",name:"WASH",task:"Self-trade heuristics.",last:"scan 22s"},{id:"mint",name:"MINT",task:"New collections. Observe only.",last:"scan 30s"},{id:"social",name:"SOCIAL",task:"X human vs farm heuristic.",last:"scan 2m"},{id:"risk",name:"RISK",task:"Proxy / phishing flags.",last:"scan 14s"}];
function S(human,farm,note){return{posts6h:0,views:0,likes:0,replies:0,quotes:0,human,farm,reach:40,note,sample:{who:"-",text:note,eng:""}};}
const DEMO=[{slug:"cryptopunks",name:"CryptoPunks",chain:"eth",floor:29.8,chg:0,vol:0,sales:0,holders:3819,supply:10000,listed:11,bid:28.4,wash:4,risk:"low",flags:["bluechip"],social:S(78,14,"Calibration. Quiet adult tape."),why:"Benchmark. Depth exists. Not a hunt signal."},{slug:"pudgypenguins",name:"Pudgy Penguins",chain:"eth",floor:3.4,chg:0,vol:0,sales:0,holders:4701,supply:8888,listed:8,bid:3.1,wash:9,risk:"low",flags:["brand"],social:S(71,22,"Brand / retail IP talk."),why:"Brand + tighter list. Compare live floor to OpenSea."},{slug:"argonauts",name:"Argonauts",chain:"eth",floor:0.52,chg:0,vol:0,sales:0,holders:2266,supply:9213,listed:8,bid:0.31,wash:18,risk:"med",flags:["run","thin-bid"],social:S(64,28,"Humans plus labeled salesbot."),why:"Real tape, thin bid. Check gap before paper."},{slug:"azuki",name:"Azuki",chain:"eth",floor:0.68,chg:0,vol:0,sales:0,holders:4387,supply:10000,listed:8,bid:0.62,wash:10,risk:"low",flags:["mid-book"],social:S(63,22,"Quiet brand tape."),why:"Offer book classroom. Swing only if gap tightens."},{slug:"milady",name:"Milady Maker",chain:"eth",floor:0.88,chg:0,vol:0,sales:0,holders:4100,supply:10000,listed:10,bid:0.8,wash:11,risk:"med",flags:["culture"],social:S(66,24,"Culture replies from named posters."),why:"Culture bid. Listings spike is the invalidation."},{slug:"mfers",name:"mfers",chain:"eth",floor:0.14,chg:0,vol:0,sales:0,holders:5500,supply:10021,listed:6,bid:0.13,wash:8,risk:"low",flags:["cc0"],social:S(80,9,"Quiet cc0 chatter."),why:"Retail-size culture. Fine watchlist."},{slug:"lilpudgys",name:"Lil Pudgys",chain:"eth",floor:0.33,chg:0,vol:0,sales:0,holders:10460,supply:21930,listed:8,bid:0.3,wash:12,risk:"med",flags:["retail-size"],social:S(55,34,"Louder satellite of Pudgys."),why:"Compare SOCIAL to parent Pudgys."},{slug:"qft-quantum-echoes",name:"Quantum Echoes",chain:"eth",floor:0.05,chg:0,vol:0,sales:0,holders:900,supply:0,listed:12,bid:0.02,wash:25,risk:"high",flags:["observe-mint"],social:S(42,48,"Campaign-shaped mint heat."),why:"Observe-only. Do not paper a mint fill."}];
const WATCH=[{slug:"cryptopunks",role:"calibration",mode:"hold"},{slug:"pudgypenguins",role:"brand",mode:"hold"},{slug:"argonauts",role:"active-run",mode:"swing"},{slug:"azuki",role:"mid-book",mode:"swing"},{slug:"milady",role:"culture",mode:"swing"},{slug:"mfers",role:"culture-cheap",mode:"swing"},{slug:"lilpudgys",role:"retail-size",mode:"swing"},{slug:"qft-quantum-echoes",role:"observe-mint",mode:"observe"}];
const WATCH_SLUGS=WATCH.map(w=>w.slug);
let rows=DEMO.slice();let filter="watch";let selected="argonauts";let live=false;
function sx(c){return (c.social&&typeof c.social==="object")?c.social:S(50,20,"");}
function watchMeta(c){return WATCH.find(w=>w.slug===c.slug)||{role:"tape",mode:"watch"};}
function modeOf(c){return watchMeta(c).mode;}
function roleOf(c){return watchMeta(c).role;}
function scoreOf(c){const s=sx(c);const run=Math.max(-20,Math.min(40,c.chg||0))*0.55;const liq=Math.log10((c.vol||1)+1)*8;const book=c.floor?(c.bid/c.floor)*18:0;const hold=Math.min(18,(c.holders/Math.max(c.supply||c.holders,1))*26);const social=(s.human*0.18)+(s.reach*0.05)-(s.farm*0.22);const riskPen=c.risk==="high"?18:c.risk==="med"?7:0;return Math.max(1,Math.min(99,Math.round(28+run+liq+book+hold+social-(c.wash||0)*0.35-riskPen)));}
function chgClass(n){return n>1?"up":n<-1?"down":"flat";}
function fmtEth(n){const x=Number(n);if(!x)return "-";if(x>=10)return x.toFixed(2);if(x>=0.1)return x.toFixed(3);return x.toFixed(4);}
function renderBots(){document.getElementById("bots").innerHTML=BOTS.map(b=>`<article class="bot on"><div class="top"><div class="name">${b.name}</div><span class="pill live">${b.id==="social"?"X":"ON"}</span></div><p>${b.task}</p><div class="meta">${b.last}</div></article>`).join("");}
function renderFilters(){const tabs=[["watch","Starter 8"],["run","Runs"],["human","Human X"],["farmed","Farmed X"],["observe","Observe"],["all","All tape"]];document.getElementById("filters").innerHTML=tabs.map(([id,label])=>`<button data-f="${id}" class="${filter===id?"on":""}">${label}</button>`).join("");document.querySelectorAll("#filters button").forEach(btn=>{btn.onclick=()=>{filter=btn.dataset.f;renderTable();renderFilters();};});}
function visible(){return rows.filter(c=>{if(filter==="watch")return WATCH_SLUGS.includes(c.slug);if(filter==="run")return (c.chg||0)>=15;if(filter==="human")return sx(c).human>=60&&sx(c).farm<35;if(filter==="farmed")return sx(c).farm>=50;if(filter==="observe")return (c.flags||[]).includes("observe-mint")||modeOf(c)==="observe";return true;}).sort((a,b)=>scoreOf(b)-scoreOf(a));}
function renderTable(){document.getElementById("rows").innerHTML=visible().map(c=>{const s=scoreOf(c);return `<tr data-slug="${c.slug}" class="${selected===c.slug?"sel":""}"><td><div class="col"><div class="thumb"></div><div><div>${c.name}</div><div class="slug">${c.chain} · ${roleOf(c)} · ${modeOf(c)}</div></div></div></td><td class="mono">${fmtEth(c.floor)} ETH</td><td class="${chgClass(c.chg)}">${c.chg>0?"+":""}${Number(c.chg||0).toFixed(1)}%</td><td>${Number(c.vol||0).toFixed(1)}</td><td>${c.sales||0}</td><td>${Number(c.holders||0).toLocaleString()}</td><td>${c.listed||0}%</td><td class="up">${sx(c).human}</td><td class="${sx(c).farm>=50?"down":"flat"}">${sx(c).farm}</td><td><div class="score">${s}</div><div class="bar"><i style="width:${s}%"></i></div></td><td><div class="flags">${(c.flags||[]).map(f=>`<span class="flag ok">${f}</span>`).join("")}</div></td></tr>`;}).join("");document.querySelectorAll("#rows tr").forEach(tr=>{tr.onclick=()=>{selected=tr.dataset.slug;renderTable();renderDetail();};});}
function renderTape(){document.getElementById("tape").innerHTML=`<div class="event social"><time>live</time><b>CIO</b><p>Connect live for OpenSea floors. SOCIAL notes are still heuristic.</p></div>`;}
function renderDetail(){const c=rows.find(x=>x.slug===selected)||rows[0];const so=sx(c);const spread=c.floor?(((c.floor-c.bid)/c.floor)*100).toFixed(1):"-";document.getElementById("detail").innerHTML=`<h2 style="margin-top:18px">CIO note</h2><div class="detail"><div class="slug">${c.chain} · ${roleOf(c)} · ${modeOf(c)}</div><h3>${c.name}</h3><div class="kpis"><div class="kpi"><label>Desk score</label><strong>${scoreOf(c)}/99</strong></div><div class="kpi"><label>Bid / floor gap</label><strong>${spread}%</strong></div><div class="kpi"><label>Wash</label><strong>${c.wash||0}</strong></div><div class="kpi"><label>Risk</label><strong>${c.risk||"-"}</strong></div></div><div class="social-box"><div class="slug">SOCIAL</div><div class="meters"><div><label><span>Human</span><span>${so.human}</span></label><div class="meter"><i class="human" style="width:${so.human}%"></i></div></div><div><label><span>Farm</span><span>${so.farm}</span></label><div class="meter"><i class="bot" style="width:${so.farm}%"></i></div></div></div><p style="color:var(--dim);font-size:12px">${so.note||""}</p></div><div class="verdict"><b>Mastermind.</b> ${c.why} No bot sends a buy.</div><div class="actions"><button class="good" onclick="paper('${c.slug}','swing')">Paper swing x1</button><button class="good" onclick="paper('${c.slug}','hold')">Paper hold x1</button><button onclick="paper('${c.slug}','pass')">Log pass</button><button class="warn" onclick="closePaper('${c.slug}')">Close vs bid</button></div></div>`;}
function setMode(isLive){live=isLive;document.getElementById("modeLabel").innerHTML=isLive?'<span class="status-dot"></span>LIVE OPENSEA':'<span class="status-dot demo"></span>DEMO TAPE';}
function loadBlotter(){try{return JSON.parse(localStorage.getItem("sightline_blotter")||"[]");}catch{return[];}}
function saveBlotter(r){localStorage.setItem("sightline_blotter",JSON.stringify(r));}
function clearBlotter(){if(!loadBlotter().length){alert("Blotter already empty.");return;}if(!confirm("Erase all paper trades on this browser?"))return;localStorage.removeItem("sightline_blotter");renderBlotter();}
function paper(slug,side){const c=rows.find(x=>x.slug===slug);if(!c)return;if(modeOf(c)==="observe"&&side!=="pass"&&!confirm("Observe-only. Paper anyway?"))return;const all=loadBlotter();all.unshift({id:Date.now(),slug,name:c.name,side,qty:side==="pass"?0:1,entry:c.floor,bid:c.bid,floor:c.floor,human:sx(c).human,farm:sx(c).farm,open:side!=="pass",ts:new Date().toISOString()});saveBlotter(all);renderBlotter();alert(side==="pass"?"Pass logged.":"Paper "+side+" opened at floor "+c.floor);}
function closePaper(slug){const all=loadBlotter();const rec=all.find(r=>r.slug===slug&&r.open);if(!rec){alert("No open paper on this name.");return;}const c=rows.find(x=>x.slug===slug)||rec;const exit=c.bid||rec.bid;rec.open=false;rec.exit=exit;rec.pl=+(((exit-rec.entry)/rec.entry)-0.05).toFixed(4);saveBlotter(all);renderBlotter();alert("Closed vs bid "+exit+" · net "+(rec.pl*100).toFixed(1)+"%");}
function renderBlotter(){const all=loadBlotter();const empty=document.getElementById("blotterEmpty");const table=document.getElementById("blotterTable");const body=document.getElementById("blotterRows");if(!all.length){empty.style.display="block";table.style.display="none";return;}empty.style.display="none";table.style.display="table";body.innerHTML=all.map(r=>{const mark=r.open?(rows.find(x=>x.slug===r.slug)?.bid??r.bid):r.exit;const pl=r.open?((mark-r.entry)/r.entry-0.05):r.pl;const cls=pl>0?"up":pl<0?"down":"flat";return `<tr><td class="slug">${r.ts.slice(5,16)}</td><td>${r.name}</td><td>${r.side}${r.open?" · open":""}</td><td>${r.qty}</td><td>${r.entry}</td><td>${mark}</td><td class="${cls}">${r.side==="pass"?"-":(pl*100).toFixed(1)+"%"}</td><td>${r.open?`<button onclick="closePaper('${r.slug}')">close</button>`:""}</td></tr>`;}).join("");}
function numish(v){if(v==null||v==="")return 0;if(typeof v==="number")return Number.isFinite(v)?v:0;if(typeof v==="string"){const n=Number(String(v).replace(/[^\d.eE+-]/g,""));return Number.isFinite(n)?n:0;}if(typeof v==="object")return numish(v.value??v.unit??v.eth??v.amount??v.floorPrice??v.floor_price);return 0;}
function pick(obj,keys){if(!obj)return 0;for(const k of keys){let cur=obj;for(const p of k.split("."))cur=cur&&cur[p];const n=numish(cur);if(n)return n;}return 0;}
function orderEth(payload){if(!payload)return 0;const o=payload.listings?.[0]||payload.offers?.[0]||payload.orders?.[0]||payload;const p=o.price||o.current_price||o.best_price||o;const nested=p.current||p;let n=numish(nested.value??nested.unit??nested.eth??nested.amount??nested);if(n>1e6)n=n/1e18;return n;}
async function osGet(path,key){const res=await fetch("https://api.opensea.io/api/v2"+path,{headers:{"X-API-KEY":key}});const text=await res.text();if(!res.ok)throw new Error(path+" HTTP "+res.status);return JSON.parse(text);}
async function osGetSoft(path,key){try{return await osGet(path,key);}catch{return null;}}
async function connectLive(){const key=document.getElementById("apiKey").value.trim();if(!key){alert("Paste your OpenSea key first.");return;}try{localStorage.setItem("sightline_os_key",key);}catch{}document.getElementById("modeLabel").innerHTML='<span class="status-dot"></span>FETCHING…';try{const liveRows=[];for(const w of WATCH){const demo=DEMO.find(d=>d.slug===w.slug)||{};const [colRaw,statsRaw,listingsRaw,offersRaw,floorsRaw]=await Promise.all([osGetSoft("/collections/"+w.slug,key),osGetSoft("/collections/"+w.slug+"/stats",key),osGetSoft("/listings/collection/"+w.slug+"/best?limit=1",key),osGetSoft("/offers/collection/"+w.slug+"/best?limit=1",key),osGetSoft("/collections/"+w.slug+"/floor_prices?timeframe=one_day",key)]);const c=(colRaw&&(colRaw.name?colRaw:(colRaw.collection&&typeof colRaw.collection==="object"?colRaw.collection:colRaw)))||{};const total=(statsRaw&&(statsRaw.total||statsRaw.stats||statsRaw))||{};const intervals=(statsRaw&&statsRaw.intervals)||[];const day=intervals.find(i=>i.interval==="one_day"||i.interval==="1d")||{};let floor=pick(total,["floorPrice","floor_price"])||orderEth(listingsRaw);let bid=orderEth(offersRaw);if(floor&&bid>floor)bid=0;let chg=0;const pts=floorsRaw&&(floorsRaw.prices||floorsRaw.floor_prices||floorsRaw.data||floorsRaw);if(Array.isArray(pts)&&pts.length>=2){const a=numish(pts[0].price??pts[0].value??pts[0]);const b=numish(pts[pts.length-1].price??pts[pts.length-1].value??pts[pts.length-1]);if(a>0&&b>0)chg=((b-a)/a)*100;}const ok=floor>0;liveRows.push({...demo,slug:(typeof c.collection==="string"?c.collection:null)||w.slug,name:c.name||demo.name||w.slug,chain:(c.contracts&&c.contracts[0]&&c.contracts[0].chain)||"ethereum",floor:ok?floor:0,chg,vol:pick(day,["volume"])||pick(total,["one_day_volume","oneDayVolume"]),sales:pick(day,["sales"])||pick(total,["one_day_sales","oneDaySales"]),holders:pick(total,["numOwners","num_owners","owners"])||demo.holders||0,supply:pick(c,["total_supply"])||demo.supply||0,listed:pick(c,["listed_percentage"])||demo.listed||0,bid:bid||(ok?+(floor*0.9).toFixed(4):0),flags:Array.from(new Set([...(demo.flags||[]).filter(f=>f!=="live-miss"),ok?"live":"live-miss"])),why:ok?(demo.why||"Live OpenSea stats."):"Floor missing for this slug."});}rows=liveRows;if(!rows.find(r=>r.slug===selected))selected=rows[0].slug;filter="watch";setMode(true);renderTable();renderDetail();renderBlotter();}catch(err){const msg=String(err.message||err);setMode(false);alert((/Failed to fetch|CORS|Load failed/i.test(msg)?"Browser blocked OpenSea.":"Live failed: "+msg)+"\nStaying on demo.");}}
try{const saved=localStorage.getItem("sightline_os_key");if(saved)document.getElementById("apiKey").value=saved;}catch(e){}
document.getElementById("tabRadar").onclick=()=>{document.body.classList.remove("view-blotter");document.getElementById("radarWrap").style.display="block";document.getElementById("blotterWrap").style.display="none";document.getElementById("tabRadar").classList.add("on");document.getElementById("tabBlotter").classList.remove("on");};
document.getElementById("tabBlotter").onclick=()=>{document.body.classList.add("view-blotter");document.getElementById("radarWrap").style.display="none";document.getElementById("blotterWrap").style.display="block";document.getElementById("tabRadar").classList.remove("on");document.getElementById("tabBlotter").classList.add("on");renderBlotter();};
document.getElementById("btnClearBlotter").onclick=clearBlotter;
document.getElementById("btnLive").onclick=connectLive;
document.getElementById("btnDemo").onclick=()=>{rows=DEMO.slice();selected="argonauts";setMode(false);renderTable();renderDetail();};
renderBots();renderFilters();renderTable();renderTape();renderDetail();renderBlotter();
